export const FETCH_STOCK_REQUEST = 'FETCH_STOCK_REQUEST';
export const FETCH_STOCK_SUCCESS = 'FETCH_STOCK_SUCCESS';
export const FETCH_STOCK_FAILURE = 'FETCH_STOCK_FAILURE';
export const CHANGE_FILTER = 'CHANGE_FILTER';
export const FETCH_COMPANY_SUCCESS = 'FETCH_COMPANY_SUCCESS';
